gradio:
  flagging_dir: "flagged"
  allow_flagging: "auto"
  share: True
llama_index:
  data_dir: "toy_data"
  persist_dir: "storage"
  model: "gpt-3.5-turbo"
  temperature: 0
  chunk_size: 512
  similarity_top_k: 3
  streaming: True
